# Site settings
title: Jiaxuan Li
positin: Senior Undergraduate
email: jiaxuan_li@pku.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage of Jiaxuan Li, a senior Student in Department of Astronomy, Peking University. <br>
  Enjoy galaxies, cosmology and supernovae! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://astrojacobli.github.io" # the base hostname & protocol for your site
twitter_username: JiaxuanLiPKU
github_username:  AstroJacobLi
orcid: 0000-0001-9592-4190
# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Junior Undergraduate"
excerpt_separator: "<!--more-->"

# This will require each of these plugins automatically.
plugins:
  - image
  - jekyll-seo-tag
# SEO stuff
twitter:
  username: JiaxuanLiPKU
  card: summary
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""